name: Roq Site Deploy

on:
  push:
    branches: [ main ]   # Switch to the branch which should be deployed to GitHub Pages
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate Roq Site
        uses: quarkiverse/quarkus-roq@v1
        with:
          github-pages: false
      - name: Publishing blog
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: target/roq
          retention-days: 3
  deploy:
    name: 'Deploy to Netlify'
    steps:
      - uses: jsmrcaga/action-netlify-deploy@v2.0.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          NETLIFY_DEPLOY_TO_PROD: false
          build_directory: target/roq